version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./public:/var/www
      - ./nginx/etc/letsencrypt:/etc/letsencrypt